### ISSUE TITLE
Can't subscribe a student to WEI

### ISSUE THREAD

**Issue by Crocmagnon** [BdEINSALyon/marsu#7]
I'm unable to look for a student in the WEI tab (maybe it's because none are subscribed yet).

I can't either subscribe a student, I get a 500 error. I already created a bus and a bungalow.

**Comment by Crocmagnon** [comment]
Here is a log dump :

```
2016-09-04T08:32:16.094188+00:00 heroku[router]: at=info method=GET path="/wei/wei_registrations/new" host=adhesion-bde.herokuapp.com request_id=216c18f0-d889-434f-8a84-c33d4d3d7bd7 fwd="XX" dyno=web.1 connect=0ms service=10ms status=500 bytes=1669
2016-09-04T08:32:16.093821+00:00 app[web.1]: I, [2016-09-04T08:32:16.093736 #3]  INFO -- : [216c18f0-d889-434f-8a84-c33d4d3d7bd7] Started GET "/wei/wei_registrations/new" for XX at 2016-09-04 08:32:16 +0000
2016-09-04T08:32:16.094851+00:00 app[web.1]: I, [2016-09-04T08:32:16.094788 #3]  INFO -- : [216c18f0-d889-434f-8a84-c33d4d3d7bd7] Processing by WeiRegistrationsController#new as HTML
2016-09-04T08:32:16.097254+00:00 app[web.1]: D, [2016-09-04T08:32:16.097188 #3] DEBUG -- : [216c18f0-d889-434f-8a84-c33d4d3d7bd7]   Wei Load (0.7ms)  SELECT  "weis".* FROM "weis" WHERE "weis"."enabled" = $1 ORDER BY "weis"."id" DESC LIMIT $2  [["enabled", true], ["LIMIT", 1]]
2016-09-04T08:32:16.100832+00:00 app[web.1]: I, [2016-09-04T08:32:16.100765 #3]  INFO -- : [216c18f0-d889-434f-8a84-c33d4d3d7bd7] Completed 500 Internal Server Error in 6ms (ActiveRecord: 0.7ms)
2016-09-04T08:32:16.101629+00:00 app[web.1]: F, [2016-09-04T08:32:16.101573 #3] FATAL -- : [216c18f0-d889-434f-8a84-c33d4d3d7bd7]
2016-09-04T08:32:16.101712+00:00 app[web.1]: F, [2016-09-04T08:32:16.101661 #3] FATAL -- : [216c18f0-d889-434f-8a84-c33d4d3d7bd7] NoMethodError (undefined method `students' for nil:NilClass):
2016-09-04T08:32:16.101763+00:00 app[web.1]: F, [2016-09-04T08:32:16.101717 #3] FATAL -- : [216c18f0-d889-434f-8a84-c33d4d3d7bd7]
2016-09-04T08:32:16.101811+00:00 app[web.1]: F, [2016-09-04T08:32:16.101766 #3] FATAL -- : [216c18f0-d889-434f-8a84-c33d4d3d7bd7] app/controllers/wei_registrations_controller.rb:25:in `new'
```

**Comment by PhilippeGeek** [comment]
Please retry with latest versions

**Comment by Crocmagnon** [comment]
Still 500

```
2016-09-04T13:35:47.996944+00:00 heroku[router]: at=info method=GET path="/wei/wei_registrations/new" host=adhesion-bde.herokuapp.com request_id=d019e83a-ad93-4d19-ad59-9262279bb464 fwd="XX" dyno=web.1 connect=0ms service=9ms status=500 bytes=1669
2016-09-04T13:35:47.985394+00:00 app[web.1]: I, [2016-09-04T13:35:47.985302 #3]  INFO -- : [d019e83a-ad93-4d19-ad59-9262279bb464] Started GET "/wei/wei_registrations/new" for XX at 2016-09-04 13:35:47 +0000
2016-09-04T13:35:47.986413+00:00 app[web.1]: I, [2016-09-04T13:35:47.986354 #3]  INFO -- : [d019e83a-ad93-4d19-ad59-9262279bb464] Processing by WeiRegistrationsController#new as HTML
2016-09-04T13:35:47.988694+00:00 app[web.1]: D, [2016-09-04T13:35:47.988622 #3] DEBUG -- : [d019e83a-ad93-4d19-ad59-9262279bb464]   Wei Load (0.6ms)  SELECT  "weis".* FROM "weis" WHERE "weis"."enabled" = $1 ORDER BY "weis"."id" DESC LIMIT $2  [["enabled", true], ["LIMIT", 1]]
2016-09-04T13:35:47.991668+00:00 app[web.1]: I, [2016-09-04T13:35:47.991560 #3]  INFO -- : [d019e83a-ad93-4d19-ad59-9262279bb464] Completed 500 Internal Server Error in 5ms (ActiveRecord: 0.6ms)
2016-09-04T13:35:47.992196+00:00 app[web.1]: F, [2016-09-04T13:35:47.992136 #3] FATAL -- : [d019e83a-ad93-4d19-ad59-9262279bb464]
2016-09-04T13:35:47.992284+00:00 app[web.1]: F, [2016-09-04T13:35:47.992224 #3] FATAL -- : [d019e83a-ad93-4d19-ad59-9262279bb464] NoMethodError (undefined method `students' for nil:NilClass):
2016-09-04T13:35:47.992331+00:00 app[web.1]: F, [2016-09-04T13:35:47.992272 #3] FATAL -- : [d019e83a-ad93-4d19-ad59-9262279bb464]
2016-09-04T13:35:47.992387+00:00 app[web.1]: F, [2016-09-04T13:35:47.992327 #3] FATAL -- : [d019e83a-ad93-4d19-ad59-9262279bb464] app/controllers/wei_registrations_controller.rb:25:in `new'
```

**Comment by PhilippeGeek** [comment]
You have no Wei setuped on your test environement, please create one in administration before trying to add bungalows and/or bus and/or students to a Wei.

**Comment by Crocmagnon** [comment]
Could it be possible to add an explicit error message about this ?
