### ISSUE TITLE
Broken admin

### ISSUE THREAD

**Issue by Crocmagnon** [BdEINSALyon/marsu#9]
Admin interface throws 500

```
2016-09-04T13:37:08.194686+00:00 heroku[router]: at=info method=GET path="/admin" host=adhesion-bde.herokuapp.com request_id=440aab7f-33f6-477a-bf72-94144d6873a3 fwd="XX" dyno=web.1 connect=0ms service=87ms status=500 bytes=1669
2016-09-04T13:37:08.110835+00:00 app[web.1]: I, [2016-09-04T13:37:08.110741 #3]  INFO -- : [440aab7f-33f6-477a-bf72-94144d6873a3] Started GET "/admin" for XX at 2016-09-04 13:37:08 +0000
2016-09-04T13:37:08.112270+00:00 app[web.1]: I, [2016-09-04T13:37:08.112191 #3]  INFO -- : [440aab7f-33f6-477a-bf72-94144d6873a3] Processing by Admin::DashboardController#index as HTML
2016-09-04T13:37:08.115396+00:00 app[web.1]: D, [2016-09-04T13:37:08.115336 #3] DEBUG -- : [440aab7f-33f6-477a-bf72-94144d6873a3]   User Load (0.9ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 3], ["LIMIT", 1]]
2016-09-04T13:37:08.125857+00:00 app[web.1]: D, [2016-09-04T13:37:08.125763 #3] DEBUG -- : [440aab7f-33f6-477a-bf72-94144d6873a3]   Role Load (1.5ms)  SELECT "roles".* FROM "roles" INNER JOIN "users_roles" ON "roles"."id" = "users_roles"."role_id" WHERE "users_roles"."user_id" = $1 AND (((roles.name = 'admin') AND (roles.resource_type IS NULL) AND (roles.resource_id IS NULL)))  [["user_id", 3]]
2016-09-04T13:37:08.127831+00:00 app[web.1]: D, [2016-09-04T13:37:08.127779 #3] DEBUG -- : [440aab7f-33f6-477a-bf72-94144d6873a3]   Role Load (0.7ms)  SELECT "roles".* FROM "roles" INNER JOIN "users_roles" ON "roles"."id" = "users_roles"."role_id" WHERE "users_roles"."user_id" = $1 AND (((roles.name = 'cowei') AND (roles.resource_type IS NULL) AND (roles.resource_id IS NULL)))  [["user_id", 3]]
2016-09-04T13:37:08.130243+00:00 app[web.1]: D, [2016-09-04T13:37:08.130185 #3] DEBUG -- : [440aab7f-33f6-477a-bf72-94144d6873a3]   Role Load (0.7ms)  SELECT "roles".* FROM "roles" INNER JOIN "users_roles" ON "roles"."id" = "users_roles"."role_id" WHERE "users_roles"."user_id" = $1 AND (((roles.name = 'permanencier') AND (roles.resource_type IS NULL) AND (roles.resource_id IS NULL)))  [["user_id", 3]]
2016-09-04T13:37:08.132074+00:00 app[web.1]: D, [2016-09-04T13:37:08.132023 #3] DEBUG -- : [440aab7f-33f6-477a-bf72-94144d6873a3]   Role Load (0.7ms)  SELECT "roles".* FROM "roles" INNER JOIN "users_roles" ON "roles"."id" = "users_roles"."role_id" WHERE "users_roles"."user_id" = $1 AND (((roles.name = 'trezo') AND (roles.resource_type IS NULL) AND (roles.resource_id IS NULL)))  [["user_id", 3]]
2016-09-04T13:37:08.133029+00:00 app[web.1]: I, [2016-09-04T13:37:08.132974 #3]  INFO -- : [440aab7f-33f6-477a-bf72-94144d6873a3]   Rendering vendor/bundle/ruby/2.3.0/bundler/gems/activeadmin-0a5a15b88bff/app/views/active_admin/page/index.html.arb
2016-09-04T13:37:08.173143+00:00 app[web.1]: D, [2016-09-04T13:37:08.173048 #3] DEBUG -- : [440aab7f-33f6-477a-bf72-94144d6873a3]    (8.1ms)  SELECT COUNT(*) AS count_all, (DATE_TRUNC('day', (students.updated_at::timestamptz - INTERVAL '0 second') AT TIME ZONE 'Etc/UTC') + INTERVAL '0 second') AT TIME ZONE 'Etc/UTC' AS date_trunc_day_students_updated_at_timestamptz_interval_0_secon FROM "students" INNER JOIN "payments" ON "payments"."student_id" = "students"."id" AND ("payments"."id" NOT IN (SELECT "payments"."id" FROM "payments" WHERE "payments"."refunded" = $1)) AND "payments"."payable_type" = $2 INNER JOIN "memberships" ON "memberships"."id" = "payments"."payable_id" WHERE (memberships.start_date <= '2016-09-04' AND memberships.end_date >= '2016-09-04') AND (students.updated_at IS NOT NULL) GROUP BY (DATE_TRUNC('day', (students.updated_at::timestamptz - INTERVAL '0 second') AT TIME ZONE 'Etc/UTC') + INTERVAL '0 second') AT TIME ZONE 'Etc/UTC'  [["refunded", true], ["payable_type", "Membership"]]
2016-09-04T13:37:08.183752+00:00 app[web.1]: D, [2016-09-04T13:37:08.183671 #3] DEBUG -- : [440aab7f-33f6-477a-bf72-94144d6873a3]   Wei Load (1.4ms)  SELECT  "weis".* FROM "weis" WHERE "weis"."enabled" = $1 ORDER BY "weis"."id" DESC LIMIT $2  [["enabled", true], ["LIMIT", 1]]
2016-09-04T13:37:08.192956+00:00 app[web.1]: I, [2016-09-04T13:37:08.192893 #3]  INFO -- : [440aab7f-33f6-477a-bf72-94144d6873a3]   Rendered vendor/bundle/ruby/2.3.0/bundler/gems/activeadmin-0a5a15b88bff/app/views/active_admin/page/index.html.arb (59.6ms)
2016-09-04T13:37:08.193292+00:00 app[web.1]: I, [2016-09-04T13:37:08.193242 #3]  INFO -- : [440aab7f-33f6-477a-bf72-94144d6873a3] Completed 500 Internal Server Error in 81ms (ActiveRecord: 14.0ms)
2016-09-04T13:37:08.194984+00:00 app[web.1]: F, [2016-09-04T13:37:08.194934 #3] FATAL -- : [440aab7f-33f6-477a-bf72-94144d6873a3]
2016-09-04T13:37:08.195060+00:00 app[web.1]: F, [2016-09-04T13:37:08.195012 #3] FATAL -- : [440aab7f-33f6-477a-bf72-94144d6873a3] ActionView::Template::Error (undefined method `name' for nil:NilClass):
2016-09-04T13:37:08.195304+00:00 app[web.1]: F, [2016-09-04T13:37:08.195210 #3] FATAL -- : [440aab7f-33f6-477a-bf72-94144d6873a3]     1: insert_tag active_admin_application.view_factory["page"]
2016-09-04T13:37:08.195374+00:00 app[web.1]: F, [2016-09-04T13:37:08.195324 #3] FATAL -- : [440aab7f-33f6-477a-bf72-94144d6873a3]
2016-09-04T13:37:08.195441+00:00 app[web.1]: F, [2016-09-04T13:37:08.195394 #3] FATAL -- : [440aab7f-33f6-477a-bf72-94144d6873a3] app/admin/dashboard.rb:19:in `block (5 levels) in <top (required)>'
2016-09-04T13:37:08.195505+00:00 app[web.1]: F, [2016-09-04T13:37:08.195459 #3] FATAL -- : [440aab7f-33f6-477a-bf72-94144d6873a3] app/admin/dashboard.rb:17:in `block (4 levels) in <top (required)>'
2016-09-04T13:37:08.195571+00:00 app[web.1]: F, [2016-09-04T13:37:08.195524 #3] FATAL -- : [440aab7f-33f6-477a-bf72-94144d6873a3] app/admin/dashboard.rb:16:in `block (3 levels) in <top (required)>'
2016-09-04T13:37:08.195636+00:00 app[web.1]: F, [2016-09-04T13:37:08.195590 #3] FATAL -- : [440aab7f-33f6-477a-bf72-94144d6873a3] app/admin/dashboard.rb:9:in `block (2 levels) in <top (required)>'
```

**Comment by PhilippeGeek** [comment]
Oh yes, I know why, fixed in next push

**Comment by Crocmagnon** [comment]
Still 500
